# Generated by Django 6.0 on 2026-01-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_profile_image_user_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='leave',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
